version: "3.9"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: intro
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  web:
    build: app/backend
    command: runserver
    volumes:
      - ./app/backend:/app
    env_file:
      - dev.env
    ports:
      - "8000:8000"